{{- if .Values.buildconfig.enabled }}
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: {{ .Values.buildconfig.git.uri | quote }}
  name: {{ include "quarkus-app.fullname" . }}
  labels:
    app: {{ include "quarkus-app.fullname" . }}
    app.kubernetes.io/component: {{ include "quarkus-app.fullname" . }}
    app.kubernetes.io/instance: {{ include "quarkus-app.fullname" . }}
    app.kubernetes.io/name: {{ include "quarkus-app.fullname" . }}
    app.kubernetes.io/part-of: {{ include "quarkus-app.fullname" . }}
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  lookupPolicy:
    local: false
{{ end }}