# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Kubernetes details
route: false
deployment: true
deploymentConfig: false
replicas:
  min: 1
  max: 2

# Image details
image_repository: quay.io
image_name: generic-app
image_namespace: imagen-namespace
image_version: latest

# Build configuration
buildconfig: 
  enabled: true
  runtime: java
  runtimeVersion: openjdk-17-ubi8
  git:
    repo: https://github.com/firefighters-sre/helm-charts

# Image stream tag details
istag:
  enabled: true

# Monitoring and metrics
prometheus:
  namespace: prometheus-namespace
  servicemonitor:
    enabled: false
  podmonitor:
    enabled: false
  slos:
    enabled: false
    severity: warning
  slas:
    enabled: false
    severity: critical

# Autoscaling
hpa:
  enabled: false
  cpuTarget: 200m
  memTarget: 300Mi

# Pod disruption budgets
pdb:
  enabled: false

# Service mesh details
istio:
  enabled: false
  mtls: false
  domain: apps.hivec.sandbox209.opentlc.com
