{{- if .Values.prometheus.podmonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "concierge-app.fullname" . }}
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    {{- include "concierge-app.labels" . | nindent 4 }}
    app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  podMetricsEndpoints:
    - interval: 15s
      path: /q/metrics
      targetPort: 8080
      scheme: http
  selector:
    matchLabels:
      deploymentconfig: {{ include "concierge-app.fullname" . }}
{{ end }}