{{- if .Values.istio.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "concierge-app.fullname" . }}
  labels:
    {{- include "concierge-app.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ include "concierge-app.fullname" . }}.{{ .Values.istio.domain }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "concierge-app.fullname" . }}
spec:
  hosts:
    - {{ include "concierge-app.fullname" . }}.{{ .Values.istio.domain }}
  gateways:
    - {{ include "concierge-app.fullname" . }}
  http:
    - route:
        - destination:
            host: {{ include "concierge-app.fullname" . }}
            port:
              number: 8080
          subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "concierge-app.fullname" . }}
spec:
  host: {{ include "concierge-app.fullname" . }}
  trafficPolicy:
    {{- if .Values.istio.mtls }}
    tls:
      mode: ISTIO_MUTUAL
    {{- end }}
    loadBalancer:
      simple: LEAST_CONN
  subsets:
    - name: v1
      labels:
        {{- include "concierge-app.selectorLabels" . | nindent 8 }}
{{- end }}