{{- if .Values.prometheus.servicemonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "concierge-app.fullname" . }}
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    {{- include "concierge-app.labels" . | nindent 4 }}
    app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - interval: 15s
      path: /q/metrics
      port: tcp-8080
      scheme: http
  selector:
    matchLabels:
      deploymentconfig: {{ include "concierge-app.fullname" . }}
{{ end }}